### ISSUE TITLE
Missing Steps Reference 

### ISSUE THREAD

**Issue by dkrull-CRWD** [CrowdStrike/Identity-Protection#1]
Hello, 

On step 4 under "Running the Script" of the [DCInfo](https://github.com/CrowdStrike/Identity-Protection/tree/main/DCInfo) it tells you to:

`Follow steps 1 and 2 under "Steps - Multiple Hosts" on this article to install the PS Module and generate an OAuth token for the API.`

But there is no "Steps - Multiple Hosts" in this article. 

Is there a missing step or is this instruction not needed?

**Comment by cs-tim** [comment]
Added missing Multiple Hosts section to README.md
